[project]
name = "agentic-dungeon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.11.0",
    "networkx>=3.3",
    "matplotlib>=3.9.0",
]
